#!/bin/bash

set -eou pipefail

if [ $# -lt 2 ]
then
    exit 1
fi

TESTABLE=$1
TESTED=$2

comm -3 $TESTABLE $TESTED \
    | while read repo
      do
          pushd $repo > /dev/null
          git clean -dxf > /dev/null
          popd > /dev/null
      done

cloc --include-lang=Python,Perl,C,C++ $(comm -3 $TESTABLE $TESTED)
