#!/bin/bash

set -eou pipefail

set -x

if [ $# -lt 1]
then
	echo Usage: $0 [USER@]HOST
	exit 1
fi

POWER_TARGET="$1"

POWERSCRIPT_PATH="$(mktemp obmc-apply-power.XXXXXX)"
POWERSCRIPT="$(basename "${POWERSCRIPT_PATH}")"

on_exit() {
	rm -f "${POWERSCRIPT_PATH}"
}

trap on_exit EXIT

cat > "${POWERSCRIPT_PATH}" <<-EOF
echo $((280 + 25)) > /sys/class/gpio/export
echo $((280 + 137)) > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio$((280 + 25))/direction
echo out > /sys/class/gpio/gpio$((280 + 137))/direction
echo 1 > /sys/class/gpio/gpio$((280 + 137))/value
echo 1 > /sys/class/gpio/gpio$((280 + 25))/value
EOF

scp "${POWERSCRIPT_PATH}" "${POWER_TARGET}":/tmp/"${POWERSCRIPT}"
ssh "${POWER_TARGET}" "/bin/sh -x /tmp/'${POWERSCRIPT}'"
